---
apiVersion: cert-manager.io/v1alpha2
kind: Certificate
metadata:
  name: postgres-operator-serving-cert
  namespace: vmware-poc 
  labels:
    app: postgres-operator
spec:
  dnsNames:
    - postgres-operator-webhook-service.vmware-poc.svc
    - postgres-operator-webhook-service.vmware-poc.svc.cluster.local
  issuerRef:
    kind: ClusterIssuer
    name: postgres-operator-selfsigned-clusterissuer
  secretName: postgres-operator-webhook-server-cert
