---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: postgres-operator
  namespace: default 
  labels:
    app: postgres-operator
  annotations:
    instance-image: "postgres-instance:v1.1.0-dev.4.gf51018d"
spec:
  replicas: 1
  selector:
    matchLabels:
      app: postgres-operator
  template:
    metadata:
      labels:
        app: postgres-operator
    spec:
      serviceAccountName: postgres-operator-service-account
      containers:
        - name: postgres-operator
          image: postgres-operator:v1.1.0-dev.4.gf51018d
          command: ["./manager", "--webhook-cert-directory", "/tmp/postgres-operator-webhook-server-cert-secret"]
          imagePullPolicy: IfNotPresent
          env:
          - name: POSTGRES_IMAGE_REPO
            value: postgres-instance
          - name: POSTGRES_IMAGE_TAG
            value: v1.1.0-dev.4.gf51018d
          - name: OPERATOR_IMAGE_REPO
            value: postgres-operator
          - name: OPERATOR_IMAGE_TAG
            value: v1.1.0-dev.4.gf51018d
          - name: DOCKER_REGISTRY_SECRET_NAME
            value: regsecret
          readinessProbe:
            exec:
              command:
                - cat
                - /tmp/operatorReady
            initialDelaySeconds: 3
            periodSeconds: 2
          ports:
            - containerPort: 9443
              name: webhook-server
              protocol: TCP
          volumeMounts:
            - mountPath: /tmp/postgres-operator-webhook-server-cert-secret
              name: postgres-operator-webhook-server-cert-secret
              readOnly: true
      imagePullSecrets:
        - name: regsecret
      volumes:
        - name: postgres-operator-webhook-server-cert-secret
          secret:
            defaultMode: 420
            secretName: postgres-operator-webhook-server-cert
