#@data/values
---
openshift: True #! Original value: false
namespace: vmware-postgres-operator #! Original value: default

# specify the url for the docker image for the operator, e.g. gcr.io/<my_project>/postgres-operator
operatorImageRepository:  danielepalaia/operator-openshift #! Original value: postgres-operator
operatorImageTag: latest #! Original value: v1.1.0-dev.4.gf51018d

# specify the docker image for postgres instance, e.g. gcr.io/<my_project>/postgres-instance
postgresImageRepository:  danielepalaia/postgres-instance-openshift #! Original value: postgres-instance
postgresImageTag: latest  #! Original value: v1.1.0-dev.4.gf51018d
# specify the name of the docker-registry secret to allow the cluster to authenticate with the container registry for pulling images
dockerRegistrySecretName: regsecret 
